
version: "3"
services: 
    selenium-hub:
        image: selenium/hub
        container_name: selenium-hub
        ports: 
            - "4444:4444"
    firefox:
        image: selenium/node-firefox
        environment: 
            - HUB_HOST=selenium-hub
            - NODE_MAX_INSTANCES=2
        volumes:
            - /home/info/Dev/converte_comunica_ponto:/home/info/Dev/converte_comunica_ponto
            - /home/info/Dev/coleta_online/downloads:/home/info/Dev/coleta_online/downloads
    chrome:
        image: selenium/node-chrome
        environment: 
            - HUB_HOST=selenium-hub
            - NODE_MAX_INSTANCES=2
        volumes:
            - /home/info/Dev/converte_comunica_ponto:/home/info/Dev/converte_comunica_ponto
            - /home/info/Dev/coleta_online/downloads:/home/info/Dev/coleta_online/downloads